# Set these environment variables accordingly

development:
  adapter: mysql2
  database: maasive_web_development
  username: 
  password: 

test:
  adapter: mysql2
  database: maasive_web_test
  username: 
  password: 

staging:
  adapter: mysql2
  host: 127.0.0.1
  database: maasive_web_staging
  username: 
  password: 

production:
  adapter: mysql2
  host: 127.0.0.1
  database: maasive_web_production
  username: 
  password: 
